server:
  port: 8080
  forward-headers-strategy: FRAMEWORK
  shutdown: graceful
  error:
    include-exception: off
    include-stacktrace: never
    include-message: never

spring:
  config:
    activate:
      on-profile: default
    import: classpath:config/postgres.yaml

#    include:
#      - common
#      - h2
#      - postgres

  application:
    name:  kboot-spring-data-rest-demo
