spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/conversation_db"
    username: postgres
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      mode: always

logging.level:
  org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
