spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/testdb
    #url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      mode: always

logging.level:
  org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
