-- MESSAGE
DROP TABLE IF EXISTS MESSAGE;
CREATE TABLE IF NOT EXISTS MESSAGE (
    id      VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
    text    VARCHAR(60) NOT NULL,
    date    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
