-- drop database CONVERSATION_DB;
-- CREATE DATABASE CONVERSATION_DB
--     WITH
--     OWNER = postgres
--     ENCODING = 'UTF8'
--     LC_COLLATE = 'en_US.utf8'
--     LC_CTYPE = 'en_US.utf8'
--     TABLESPACE = pg_default
--     CONNECTION LIMIT = -1;

drop table if exists message cascade;
drop table if exists conversation cascade;
drop table if exists counter_generator cascade;



CREATE TABLE IF NOT EXISTS CONVERSATION (
    ID VARCHAR(255) NOT NULL,
    HAS_ATTACHMENT BOOLEAN,
    HAS_NEW_MESSAGE BOOLEAN,
    PORTAL_ACCOUNT_ID VARCHAR(255) NOT NULL,
    REFERENCE_NR VARCHAR(255) NOT NULL,
    REFERRING_TO_FIRST_NAME VARCHAR(255),
    REFERRING_TO_LAST_NAME VARCHAR(255),
    REFERRING_TO_PARTNER_NR VARCHAR(255),
    SUBJECT VARCHAR(255),
    TYPE VARCHAR(255),
    UPDATED_ON TIMESTAMP (6) NOT NULL,
    CREATED_ON TIMESTAMP (6) NOT NULL,
    CONSTRAINT PK_CONVERSATION PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS COUNTER_GENERATOR (
    ID NUMERIC NOT NULL,
    COUNTER VARCHAR(10) NOT NULL,
    CONSTRAINT PK_COUNTER_GENERATOR PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MESSAGE(
    ID VARCHAR(255) NOT NULL,
    CREATED_ON TIMESTAMP (6) NOT NULL,
    CREATOR VARCHAR(255),
    TEXT TEXT,
    CONVERSATION_ID VARCHAR(255) constraint FK_TO_CONVERSATION references CONVERSATION,
    CONSTRAINT PK_MESSAGE PRIMARY KEY (ID)
);

